2019-06-11 13:55:51:     User(ID3161410E-aWXZngFf) was authenticated successfully
2019-06-11 13:55:51:     Search for a game...
2019-06-11 13:55:51:     Join request sent...
2019-06-11 13:55:51:     Game type = "Red bonus tile" : True, "Open tanyao" : True, "Game  length" : tonpusen
2019-06-11 13:55:51:     0 seconds passed...
2019-06-11 13:55:51:     A new game started!
2019-06-11 13:55:51:     The replay link can be found here: http://tenhou.net/0/?log=None&tw=3
2019-06-11 13:55:51:     Players are: [Toul - 新人 - None, COM - 新人 - None, COM - 新人 - None, COM - 新人 - None]
2019-06-11 13:55:55:     --------------------------------------------------
2019-06-11 13:55:55:     Players: [Toul - 新人 - 25000, COM - 新人 - 25000, COM - 新人 - 25000, COM - 新人 - 25000]
2019-06-11 13:55:55:     Dealer: COM - 新人 - 25000
2019-06-11 13:55:55:  
2019-06-11 13:55:55:     [Player 1] draws a tile...
2019-06-11 13:55:55:     [Player 2] draws a tile...
2019-06-11 13:55:55:     [Player 3] draws a tile...
2019-06-11 13:55:56: 
2019-06-11 13:55:57: 
2019-06-11 13:55:57:     Remaining tiles: 66
2019-06-11 13:55:57:     --------------------------------------------------
2019-06-11 13:55:57: 
2019-06-11 13:55:58:     [Player 1] draws a tile...
2019-06-11 13:55:59:     [Player 2] draws a tile...
2019-06-11 13:55:59:     [Player 3] draws a tile...
2019-06-11 13:56:01: 
2019-06-11 13:56:01: Unexpected exception
Traceback (most recent call last):
  File "GUI.py", line 200, in connect_and_play
    return client.start_game()
  File "D:\workspace\AIMahjong\myAI\client\tenhou_client.py", line 130, in start_game
    if self._handle_draw_tile(msg):
  File "D:\workspace\AIMahjong\myAI\client\tenhou_client.py", line 562, in _handle_draw_tile
    discard_tile_136 = self.game_table.bot.tile_34_to_136(discard_tile_34)
  File "D:\workspace\AIMahjong\myAI\client\mahjong_player.py", line 216, in tile_34_to_136
    return [t136 for t136 in self.tiles136 if tile34 == (t136 // 4)][-1]
IndexError: list index out of range
2019-06-11 13:56:01: End the game...
2019-06-11 13:56:02:     Game was ended unexpected
2019-06-11 13:56:02: 
