2019-06-10 23:59:09:     User(ID3161410E-aWXZngFf) was authenticated successfully
2019-06-10 23:59:11:     Search for a game...
2019-06-10 23:59:11:     Join request sent...
2019-06-10 23:59:11:     Game type = "Red bonus tile" : True, "Open tanyao" : True, "Game  length" : tonpusen
2019-06-10 23:59:11:     0 seconds passed...
2019-06-10 23:59:11:     A new game started!
2019-06-10 23:59:11:     The replay link can be found here: http://tenhou.net/0/?log=None&tw=2
2019-06-10 23:59:11:     Players are: [Toul - 新人 - None, COM - 新人 - None, COM - 新人 - None, COM - 新人 - None]
2019-06-10 23:59:12: Unexpected exception
Traceback (most recent call last):
  File "D:\workspace\AIMahjong\myAI\main.py", line 14, in connect_and_play
    return client.start_game()
  File "D:\workspace\AIMahjong\myAI\client\tenhou_client.py", line 119, in start_game
    '<INIT' in msg and self._handle_initial_msg(msg)
  File "D:\workspace\AIMahjong\myAI\client\tenhou_client.py", line 323, in _handle_initial_msg
    self.drawer.init_hand(tiles)
  File "GUI.py", line 291, in init_hand
    self.update_opp([], 1)
  File "GUI.py", line 594, in update_opp
    self._add_tile_image(x, y, 34, player,False)
  File "GUI.py", line 932, in _add_tile_image
    self.cvs.create_window((x,y), window=bt, anchor='nw')
UnboundLocalError: local variable 'bt' referenced before assignment
2019-06-10 23:59:12: End the game...
2019-06-10 23:59:12:     Game was ended unexpected
2019-06-10 23:59:12: 
